### ISSUE TITLE
Help! [Errno 16] Resource busy

### ISSUE THREAD

**Issue by mr-bryn** [weewx/weewx-wmr200#2]
Hi weewx group!

Firstly thank you for all the effort that has gone into this amazing package! I’ve been running weewx for my WMR200 for several years.

I’m trying to migrate weewx from a raspberry pi into a VM running on Proxmox. The WMR is connected via a USB ethernet extension adapter. The VM and USB passthrough all appears to work as the WMR200 shows up in VM’s list of usb devices and weewx reads it, etc.

The problem is I’m frequently getting the dreaded Errno 16 Resource busy error. I’ve tried running both python 2 and python 3 versions of weewx and with the latest WMR200 driver, but no difference.

When the error occurs it seems a restart of weewx is not enough. Rebooting the VM works.

Where can I start with troubleshooting? I’ve tried using a different ethernet cable (in case there was some interference, bad wiring, etc.) but this didn’t help.

I never saw this error on the raspberry pi, but I wasn't using the ethernet extension.

```
CRITICAL user.wmr200: open_device() Unable to claim USB interface. Reason: [Errno 16] Resource busy
ERROR weewx.engine: Import of driver failed: [Errno 16] Resource busy (<class 'weewx.WakeupError'>)
CRITICAL weewx.engine:     ****  Traceback (most recent call last):
CRITICAL weewx.engine:     ****    File "/usr/share/weewx/user/wmr200.py", line 195, in open_device
CRITICAL weewx.engine:     ****      self.handle.claimInterface(self.interface)
CRITICAL weewx.engine:     ****    File "/usr/lib/python3/dist-packages/usb/legacy.py", line 230, in claimInterface
CRITICAL weewx.engine:     ****      util.claim_interface(self.dev, interface)
CRITICAL weewx.engine:     ****    File "/usr/lib/python3/dist-packages/usb/util.py", line 205, in claim_interface
CRITICAL weewx.engine:     ****      device._ctx.managed_claim_interface(device, interface)
CRITICAL weewx.engine:     ****    File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
CRITICAL weewx.engine:     ****      return f(self, *args, **kwargs)
CRITICAL weewx.engine:     ****    File "/usr/lib/python3/dist-packages/usb/core.py", line 167, in managed_claim_interface
CRITICAL weewx.engine:     ****      self.backend.claim_interface(self.handle, i)
CRITICAL weewx.engine:     ****    File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 811, in claim_interf
ace
CRITICAL weewx.engine:     ****      _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
CRITICAL weewx.engine:     ****    File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
CRITICAL weewx.engine:     ****      raise USBError(_strerror(ret), ret, _libusb_errno[ret])
CRITICAL weewx.engine:     ****  usb.core.USBError: [Errno 16] Resource busy
CRITICAL weewx.engine:     ****
CRITICAL weewx.engine:     ****  During handling of the above exception, another exception occurred:
CRITICAL weewx.engine:     ****
CRITICAL weewx.engine:     ****  Traceback (most recent call last):
CRITICAL weewx.engine:     ****    File "/usr/share/weewx/weewx/engine.py", line 119, in setupStation
CRITICAL weewx.engine:     ****      self.console = loader_function(config_dict, self)
CRITICAL weewx.engine:     ****    File "/usr/share/weewx/user/wmr200.py", line 58, in loader
CRITICAL weewx.engine:     ****      return WMR200(**config_dict[DRIVER_NAME])
CRITICAL weewx.engine:     ****    File "/usr/share/weewx/user/wmr200.py", line 1470, in __init__
CRITICAL weewx.engine:     ****      self.usb_device.open_device(vendor_id, product_id)
CRITICAL weewx.engine:     ****    File "/usr/share/weewx/user/wmr200.py", line 198, in open_device
CRITICAL weewx.engine:     ****      raise weewx.WakeupError(exception)
CRITICAL weewx.engine:     ****  weewx.WakeupError: [Errno 16] Resource busy
CRITICAL __main__: Unable to load driver: [Errno 16] Resource busy
CRITICAL __main__:     ****  Exiting...
```

**Comment by mr-bryn** [comment]
Re-instated my original raspberry pi setup via the USB ethernet extension and getting the same Errno 16 Resource busy messages.

Suspect I've got a dodgy ethernet cable, so closing this issue.
